server:
  port: 9999
spring:
  jackson:
    # json 序列化排除值为 null 的属性
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  autoconfigure:
    exclude:
      # 项目中禁用MongoDB(如果使用了MongoDB，请删除下面这行)
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.ssssssss.magicapi.mongo.MagicMongoConfiguration

  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/magic-api?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: magic
    password: magic
magic-api:
  # 配置web页面入口
  web: /magic/web
#  security:
#    # 登录用的用户名
#    username: admin
#    # 登录用的密码
#    password: e10adc3949ba59abbe56e057f20f883e  # 123456的hash
  resource:
    # 配置文件存储位置。当以classpath开头时，为只读模式
    # mac用户请改为可读写的目录
    # 如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）
    location: magic-api/data
  backup: # 备份相关配置
    enable: true #是否启用
    max-history: -1 #备份保留天数，-1为永久保留
    table-name: magic_backup_record_v2 #使用数据库存储备份时的表名

api:
  token: 12345678
