server:
  port: 9999
spring:
  jackson:
    # json 序列化排除值为 null 的属性
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: xxxxxxxx
  autoconfigure:
    exclude:
      # 项目中禁用MongoDB(如果使用了MongoDB，请删除下面这行)
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.ssssssss.magicapi.mongo.MagicMongoConfiguration

  # 数据库
  datasource:
    url: jdbc:mysql://mysql:3306/magic?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: magic
    password: magic
influxdb2:
  url: http://192.168.1.70:8086
  token: admin-token==
  org: jk
  bucket: jkscada

magic-api:
  # 配置web页面入口
  web: /magic/web
  #  security:
  #    # 登录用的用户名
  #    username: admin
  #    # 登录用的密码
  #    password: e10adc3949ba59abbe56e057f20f883e  # 123456的hash
  resource: # 配置存储方式
    type: database # 配置存储在数据库中
    table-name: magic_api_file_v2 # 数据库中的表名
  backup: # 备份相关配置
    enable: true # 是否启用
    max-history: -1 # 备份保留天数，-1为永久保留
    table-name: magic_backup_record_v2 # 使用数据库存储备份时的表名
  response: |- # 配置JSON格式，格式为magic-script中的表达式
    {
      msg: message,
      result: code,
      extra: data,
    }

  response-code:
    success: 1 # 执行成功的code值
    invalid: -1 # 参数验证未通过的code值
    exception: -2 # 执行出现异常的code值

  editor-config: classpath:config/magic-editor-config.js

api:
  # 提供API访问接口时需要验证的Token，如未配置此项，或指定接口的选项中配置了不需要登录，则不会验证
  token: 12345678


