server:
  port: 9999
spring:
  jackson:
    # json 序列化排除值为 null 的属性
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/magic-api?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: magic
    password: magic
magic-api:
  # 配置web页面入口
  web: /magic/web
  security:
    # 登录用的用户名
    username: admin
    # 登录用的密码
    password: e10adc3949ba59abbe56e057f20f883e  # 123456的hash
  resource:
    # 配置文件存储位置。当以classpath开头时，为只读模式
    # mac用户请改为可读写的目录
    # 如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）
    location: magic-api/data

api:
  token: 12345678
